### ISSUE TITLE
Gene family expansions and contractions

### ISSUE THREAD

**Issue by lyy005** [hillerlab/ForwardGenomics#1]
Dear Dr. Hiller, 
I'm trying to use gene family expansion and contraction data as the input for ForwardGenomics. I was wondering how I should calculate the local and global %id if there're two copies of a gene in one species. 

Thank you for any suggestions

Yiyuan

**Comment by MichaelHiller** [comment]
Well, if you have the inferred size of a gene family for every node in the phylogeny, you could compute the per-branch difference and take this as the local %id. And computing the difference between the common ancestor and extant species could be taken as the global %id. 
But we have never tried that, so I don't know if it works
Best
Michael

**Comment by lyy005** [comment]
Thank you! That makes sense.

Yiyuan
