### ISSUE TITLE
the raw genome input for  ForwardGenomics

### ISSUE THREAD

**Issue by yuzhenpeng** [hillerlab/ForwardGenomics#12]
hi，hiller

I want use your data for  ForwardGenomics about the Loss of Vision in Blind Mammals.
But I don't know how to down the blind mammals genome: prairie vole (micOch1), blind mole rat (nanGal1), cape golden mole (chrAsi1). 
I try download the same version three geno,me from Enseble or NCBI. But I get some warnings
`
perl Maf2SpanningSeq_PRANK.perl chr7.out.maf CDS147317 -twoBitPath ./genome/ -noMissingSeq

KL204554 is not in ./genome//nanGal1/nanGal1.2bit
ERROR in getSeqTwoBitFile: set -o pipefail; echo -e "KL204554\t2832056\t2832169\tname\t1000\t-" | twoBitToFa ./genome//nanGal1/nanGal1.2bit stdout -bed=stdin -noMask failed
`

I guess the genome' header are different with your 60-way alignment in multiz.maf.

Could you help me.
Thank you.

**Comment by MichaelHiller** [comment]
Hi,

it looks like the scaffold names have been updated. The 2bit files that we got from UCSC have these KL20... names.

I have uploaded all three 2bit files to https://bds.mpi-cbg.de/hillerlab/ForwardGenomics/loss_of_vision/

Pls let me know if there are other problems. 
Michael

**Comment by yuzhenpeng** [comment]
Yeah, it works. Thank you.

**Comment by yuzhenpeng** [comment]
Dear Hiller,
I want use the Maf2SpanningSeq_PRANK.perl and GetGlobalAndLocalPercentID.perl obtain the global %id values for all elements in conservedCDS.bed in one time run (batch model) (quickly prepare the global.CDS.percentID.txt file). How should I do? What commands should be type? Could you help me. Thank you.

**Comment by MichaelHiller** [comment]
Hi Yu, 

I added a section Computing %id values to the README. Pls have a look. The scripts also output a detailed description of all parameters if you call them without any argument, and they have a verbose mode which tells you exactly what they do. 
Hope that helps
Michael

**Comment by yuzhenpeng** [comment]
> Hi Yu,
> 
> I added a section Computing %id values to the README. Pls have a look. The scripts also output a detailed description of all parameters if you call them without any argument, and they have a verbose mode which tells you exactly what they do.
> Hope that helps
> Michael

Hi Hiller,
Thanks for your rapidly response. I have read your instruction in README.
My command was put as follow:
```
mafIndex multiz.maf multiz.maf.bb -chromSizes=mm10.chrom.sizes
mafExtract multiz.maf.bb CDS.maf -regionList=conservedCDS.bed -leaveEdgeMeta  #conservedCDS.bed contains 184412 elements, so I get the whole conserved coding elements  in MAF fomat.
Maf2SpanningSeq_PRANK.perl CDS.maf allCDS -runPrank -treeFile tree.nh -keepTemporaryFiles -BDBFile testBDB # allCDS mean that I want to get all element alignment
```
But the testBDB is empty. I don't know why.

If I test one elements it works well, like:
```
mafIndex multiz.maf multiz.maf.bb -chromSizes=mm10.chrom.sizes
mafExtract multiz.maf.bb CDS147317.maf -regionList=CDS147317.bed -leaveEdgeMeta # CDS147317.bed only contains one element.
Maf2SpanningSeq_PRANK.perl CDS147317.maf CDS147317 -runPrank -treeFile tree.nh -keepTemporaryFiles -BDBFile testBDB
```
Could you give me more help. 
Thank you.

**Comment by MichaelHiller** [comment]
Hi Yu, 

the first does not work for three reasons. 1) allCDS would not be a key to retrieve these alignments from the BDB. 2) Maf2SpanningSeq_PRANK.perl assumes you give a single continuous region, not a maf that has maf blocks representing discontinuous exons of a genome. 3) You likely want to compute %id values for each exon separately (you can later compute a %id values for 1 gene by summing over all exons (sum of identical bp /  sum of alignment lengths of each exon)). Forward Genomics needs %id values for each element (here exon).  

Therefore, pls use the second version.  The BDB file then allows you to not have one output file per element. 

Michael

**Comment by yuzhenpeng** [comment]
Ok, thank you.

**Comment by yuzhenpeng** [comment]
Ok, thank you.
