### ISSUE TITLE
ForwardGenomics install on bioconda

### ISSUE THREAD

**Issue by jayramr** [hillerlab/ForwardGenomics#16]
Hi, 

Here is the recipe of https://github.com/bioconda/bioconda-recipes/pull/38319 which I created for forwardgenomics, please let me know the prerequisities and dependencies are met. 

Also kindly let me know how to test this installation to make sure it is 100% good to go

Thanks
Jay

**Comment by MichaelHiller** [comment]
Looks like this is not released in bioconda. Can you pls check?

**Comment by jayramr** [comment]
CUrrently it is waiting for merge and once it is merged it will be available in bioconda

**Comment by jayramr** [comment]
Now reflecting in bioconda
https://anaconda.org/bioconda/forwardgenomics
