### ISSUE TITLE
Question about the percent identity (%id) estimation

### ISSUE THREAD

**Issue by wendelljpereira** [hillerlab/ForwardGenomics#2]
Dear Dr. Hiller,

Thank you very much for producing this method! I have a question about the approach to generate the local %id necessary to run Forward Genomics using the branch method.

To determine the 'local %id', it is my understanding that I should proceed as follow:

1- Reconstruct the ancestors of all branches of my tree using prequel.
2- Generate the whole genome alignment between the genomes at the end of each branch with their respective ancestors.
3- Estimate the %id in each pairwise alignment generated in 2.

Is that correct? Also, I believe that these steps are not implemented in the available R code. Am I correct?

I can figure how to execute 1 and 2 trough the software manuals. However, I am wondering if it would be possible for you to share an example with the implementation that you use to calculated the %id between two genomes in a genome alignment.

Thank you!! 

Wendell Pereira

**Comment by MichaelHiller** [comment]
Dear Wendell, 

assuming you want to screen a large set of CNEs or exons, the easiest way is to 
1) produce a multiple whole genome alignment of the species of interest
2) for each CNE or exon, extract the complete sequence for every species from this alignment
3) for each CNE or exon, use Prank to align this sequence again --> Prank would reconstruct all ancestral nodes automatically and produces a full alignment of species and ancestors.
Then compute the local %id values by counting the % identical bp for each branch.

The R scripts only perform the phenotype-genotype association. We have scripts for 2) and 3) but they are customized to our compute cluster. I can share them if you like. 

Best regards
Michael

**Comment by wendelljpereira** [comment]
Dear Dr. Hiller,

Thank you very much for the quick answer! I appreciate these insights about the analysis.

It would be wonderful if you can share the scripts for 2) and 3). I am sure it will be really helpful to use them as a guide to build my own.

If you prefer to share them directly instead of posting here, this is my email: wendellpereira@ufl.edu

I still working on the multiple alignments, so it will take some time to have results. However, I am really excited with the possibility of applying your method in some of our projects.

Best Regards,
Wendell Pereira

**Comment by lyy005** [comment]
Hi Dr. Hiller,
I ran into the same issue of calculating the local %id. Thank you for the suggestions. I was wondering if I could also have the scripts for calculating local %id? My email is yli@utexas.edu

Thank you! 

YY

**Comment by MichaelHiller** [comment]
I added all scripts to the scripts/ folder. 
Best regards
Michael
