### ISSUE TITLE
new phenotype species

### ISSUE THREAD

**Issue by panpandzf** [hillerlab/ForwardGenomics#20]
Dear Professor,
I would like to ask whether "Forwardgenomics" is suitable for the analysis of CNE differences in new phenotypic species.
I wish all the best!

**Comment by MichaelHiller** [comment]
Yes, pls see https://www.cell.com/cell-reports/pdf/S2211-1247(21)01795-2.pdf and https://www.nature.com/articles/s41467-018-07122-z

**Comment by panpandzf** [comment]
Thank you very much and best wishes.

**Comment by panpandzf** [comment]
Dear Professor,
When I read your article "Convergent and lineage-specific genomic differences in limb regulatory elements in limbless reptile lineages", I learned that RERconverge was used to further confirm the results of ForwardGenomics. Complete deletion and ancestral reconstruction were removed for each CNE alignment. I don't quite understand it. Could you please explain it?  How to remove it from CNE alignment? Looking forward to your reply!
I wish all the best!

**Comment by MichaelHiller** [comment]
RERconverge and other methods that compute substitutions rates cannot handle or ignore insertions and deletions. This is why we removed species for which the entire CNE sequence was deleted. 
Forward Genomics' %id values naturally take indels into account, as they consider both substitutions and indels. 
Hope that helps

**Comment by panpandzf** [comment]
Thank you very much for your reply! I don’t know if I understand it correctly. If the entire CNE sequence of a species is completely deleted, then this species will be removed from the topology. Please forgive my possibly stupid question and I look forward to your reply.

**Comment by MichaelHiller** [comment]
Yes, exactly

**Comment by panpandzf** [comment]
Thank you very much for your enthusiastic help
