### ISSUE TITLE
perl modules missing

### ISSUE THREAD

**Issue by ghost** [hillerlab/ForwardGenomics#3]
Hi,

   The perl modules in your scripts "GetGlobalAndLocalPercentID.perl" and "Maf2SpanningSeq_PRANK.perl" including Globals.pm and MyFunctions.pm are missing, maybe others are also not supplied. Could you please add the modules in your directory? THANK YOU!

**Comment by MichaelHiller** [comment]
Done. I added Globals and changed the code as MyFunctions is not necessary. 
Please let me know if there is anything else missing.

Michael

**Comment by ghost** [comment]
Thank you! I will try it.发自我的华为手机-------- 原始邮件 --------发件人： Michael Hiller <notifications@github.com>日期： 2020年3月1日周日 22:13收件人： hillerlab/ForwardGenomics <ForwardGenomics@noreply.github.com>抄送： wangxb1 <biowangxb@163.com>, Author <author@noreply.github.com>主    题： Re: [hillerlab/ForwardGenomics] perl modules missing (#3)Done. I added Globals and changed the code as MyFunctions is not necessary.
Please let me know if there is anything else missing.
Michael
