### ISSUE TITLE
Backward Genomics? Gene gain instead of gene loss

### ISSUE THREAD

**Issue by ViriatoII** [hillerlab/ForwardGenomics#6]
Hi! 

I'm enjoying your paper very much, thank you for it. I'm rather interested in the opposite of Forward Genomics. I would like to study convergent gene gain. I guess your methods are not suitable for it?

 Do you also work on this or have an idea of what presuppositions should be made? Something also with %id and covariance matrices, but with a different presupposition in relation to neutrality?

Kind regards,
Ricardo

**Comment by MichaelHiller** [comment]
Hi Ricardo, 
correct.  Our methods cannot find convergent gene gains, as they focus on ancestral elements. I also thought of this, but I think (i) finding de novo evolved genes is hard, unless you have transcriptomics data (which one would need for many species) and (ii) by definition such convergent gains would likely be different genes with different sequences.
Best
Michael

**Comment by ViriatoII** [comment]
Thank you for the answer!

I'm following the work of a [paper](https://www.nature.com/articles/s41477-019-0486-9) that extends this concept. I do have a ton of data, including transcriptomics. The idea is to cluster predicted proteins and model the existence/ frequency of those groups against a quantitative trait, controlling for phylogenetic distance.

I might inform you if I manage to get results!

Cheers,
Ricardo
