### ISSUE TITLE
Percent Identity Values

### ISSUE THREAD

**Issue by Ran-tian** [hillerlab/ForwardGenomics#7]
Dear Dr.@MichaelHiller,

I am trying to use ForwardGenomics to estimate the divergence of CNE. I have constructed the ancestor sequences by PRANK. Next, I will estimate the percent identity between extant species and ancestors, but I am not sure whether last common ancestor of species or oldest (root) ancestors should be used here? Additionally, does the GLS or branch method will be better to estimate the divergence between species with different phenotypes.

Looking forward to your reply. Thanks.
Ran

**Comment by xieduo7** [comment]
Hi Ran,

I think [this](https://github.com/hillerlab/ForwardGenomics/issues/5#issuecomment-607959458) would be helpful for you.

Best,
Duo

**Comment by Ran-tian** [comment]
Hi Duo,
Thanks for your reply. It's really helpful.
Best,
Ran

**Comment by MichaelHiller** [comment]
Dear Ran, 


1)
In principle, the accuracy of reconstructing an internal node in a tree should be higher if you do have an outgroup species (in particular, this can be problem if you have an insertion or deletion inside your element in one of the basal branches, as reconstructing the indel history is not trivial). Thus, if you do have a proper outgroup, then I would recommend to use it (e.g. to analyze Vitamin C loss where all trait loss mammals are boreoeutherians, one can use an afrotherian mammal as a proper outgroup). 

Having said this, Prank (which we use for ancestral seq reconstruction) also reconstructs the root sequence. So if you don't really have a proper outgroup, then technically this is not a problem. 
In this case, please set the -requireNoOutgroup parameter when calling GetGlobalAndLocalPercentID.perl
Let me know if this doesn't work. 

2)
In our MBE 2016 paper, we found the branch method to be often more powerful. So I would generally recommend this. Nevertheless, you can also run both GLS and branch method and intersect or get the union of the results. 

Michael

**Comment by Ran-tian** [comment]
Dear Dr.@MichaelHiller,

Thank you for your reply!
I will try it and give you feedback later!

Thanks again,
Ran
