### ISSUE TITLE
Why not use coding regions directly?

### ISSUE THREAD

**Issue by xieduo7** [hillerlab/ForwardGenomics#8]
Hi Dr.@MichaelHiller ,

I have a question again. 

In your [Forward genomics](https://academic.oup.com/mbe/article/33/8/2135/2579415) paper, why did you use `conserved coding regions`(the intersection between conserved regions predicted by GREP or/and PhastCons and coding exons) instead of using coding exon regions directly? 

Thank you!

Best,
Duo

**Comment by MichaelHiller** [comment]
Because some parts of coding exons are not conserved. But in an earlier paper we did both (coding exons & coding exons intersected with conserved regions).

**Comment by xieduo7** [comment]
Dear Dr. @MichaelHiller ,

Why is it necessary for the input regions be conserved? This may cause false negative. 

Consider a hypothesical case: if an exon E of gene A is conserved in species 1,2 and 3 but not conserved in species 4 and 5, and a trait T is present in species 1,2,3 but absent in species 4 and 5, this exon will not be included in the input of Forward genomics. However, we cannot exclude the possiility that trait T lost because of the absent or non-conserved of E in species 4 and 5.

Best,
Duo

**Comment by MichaelHiller** [comment]
Its not necessary that the regions are conserved, but this would help to assure accurate ancestral reconstruction. 
But it is totally up to the user which regions to use as input. You can take whatever you think is best for your project. And as I said before, you could easily run both versions and compare the results if you like.
Best
Michael

**Comment by xieduo7** [comment]
Hi, @MichaelHiller ,
   
Thank you for your information!

Best,
Duo
