### ISSUE TITLE
Is i-line necessary in maf?

### ISSUE THREAD

**Issue by xieduo7** [hillerlab/ForwardGenomics#9]
Hi Dr. @MichaelHiller ,

I come across this error when run Maf2SpanningSeq_PRANK.perl:
```
ERROR: there is no i-line that follows this s-line in the maf:
```
Can I run this script without provideing i-line?

Best,
Duo

**Comment by MichaelHiller** [comment]
Hi Duo, 

this points to a potentially incorrect maf file that you are using. Every s line must be followed by an i line. If you don't have this, your format is likely corrupted. I like it when scripts actually die if they encounter such issues. 

You can add i lines to your maf with UCSC's mafAddIRows.
Best
Michael

**Comment by xieduo7** [comment]
Hi Dr.Hiller,


We didn't output the `i-line` when we produced that alignment. I used `mafAddIRows` and it works!
Thank you!

Best,
Duo
